### ISSUE TITLE
Hi, can anyone please tell me how to wrap this up to a ROS pkg for the use of my own camera?

### ISSUE THREAD

**Issue by Haotian-Zhang** [gaoxiang12/ORB-YGZ-SLAM#22]
R.T
Hi Xiang, as in official ORB-SLAM2, there's ORS package for us to build a ros wrapper for my own camera usage. Could you please tell me how to create the same thing according to your realization? @gaoxiang12 Thank you so much!

**Comment by 450932894** [comment]
Hi！
Did you find the ROS for ygz-slam? Can you share?
thank you

**Comment by Leon1998314** [comment]
Hi！
Did you find the ROS for ygz-slam?  Can you share the url?
thank you！ @Haotian-Zhang @gaoxiang12
